namespace Test_ModernMonolithicArchitecture;

public abstract class Test_ModernMonolithicArchitectureDomainTestBase : Test_ModernMonolithicArchitectureTestBase<Test_ModernMonolithicArchitectureDomainTestModule>
{

}
